export default function Inversiones() {
  return (
    <section className="paddi">
    <div className="container">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus cumque corrupti libero ipsa similique magnam itaque deserunt corporis expedita, quaerat blanditiis! Beatae, quod quia quos quibusdam mollitia, amet recusandae esse sapiente, distinctio debitis fugit tenetur consequuntur iure iste ab tempora a impedit. Nobis laborum ut eaque distinctio aspernatur doloribus itaque, quis illo. Libero natus quis architecto vero porro odio id sint accusantium optio! Quidem dolor aut dolores illo delectus dignissimos.</p>
        <p>Voluptatibus ducimus a totam ratione, laborum vel tempore aliquam perferendis omnis harum expedita voluptatum aliquid fugiat corrupti voluptates ipsa consectetur. Accusamus, autem placeat. Harum, exercitationem nam odit autem animi natus impedit, similique quasi tempora perspiciatis quas? Maxime, unde deleniti animi tempore quos quis architecto eaque molestiae sequi voluptatum, provident asperiores eligendi veritatis vitae voluptate consectetur debitis, libero ipsum? Voluptate quidem ea cupiditate, pariatur facere fugit at. Eum minima officia quia.</p>
        <p>Delectus esse, molestiae deleniti iste sint nesciunt deserunt perferendis itaque. Repellendus a reiciendis qui voluptas veritatis voluptates. Ipsum voluptas quidem suscipit nemo, iusto blanditiis maiores quo quisquam maxime similique voluptatem dicta aut illum, accusantium soluta excepturi vel reprehenderit illo explicabo fugit architecto repellendus ipsa. Natus autem iure explicabo officia fugit eligendi ullam ipsam! Repellendus quia quasi quam, perferendis fugit ullam! Odio magnam eaque tenetur aut eum reiciendis asperiores possimus amet?</p>
        <p>Dolores ducimus obcaecati modi deserunt! Velit delectus nesciunt, laborum accusantium maiores deserunt numquam eveniet tempora distinctio sequi quos vero. Nobis culpa blanditiis ullam eius ipsam sapiente rerum, iure vero! Dolor, quia beatae. Quas veniam aut, qui libero repellendus dolor fugit voluptatum delectus in cupiditate quasi ullam quibusdam reiciendis corporis earum blanditiis natus? Deserunt, neque. Dignissimos perferendis omnis nisi nemo pariatur, facilis consequatur est, sequi ipsam ab aut dolorum, suscipit repellat.</p>
        <p>Tempora suscipit, veniam iure expedita beatae nemo debitis quidem sint eligendi, eveniet error inventore laboriosam deserunt cum delectus impedit sapiente quaerat ad quis ut quo rem provident tenetur. Fuga reprehenderit atque eveniet rem velit quos dolores, hic consectetur, est dicta architecto omnis quaerat consequatur error fugiat alias aspernatur natus labore! Necessitatibus omnis beatae dolor doloremque consequuntur saepe repellat inventore magnam minima labore alias debitis, vitae voluptatum praesentium. Voluptatem, accusamus debitis?</p>
        <p>Illum quia debitis minus voluptatibus aliquam necessitatibus ab in labore eaque nobis! Consequuntur alias fuga quos dignissimos eos maxime officia nulla minus facilis fugit? Explicabo quaerat excepturi ipsum recusandae a voluptatibus, reprehenderit et dolorum maxime suscipit nam. Nemo accusamus tempora corrupti consequatur, dolorum eaque qui facere sit velit quidem consequuntur corporis vitae magni ea quisquam! Sapiente, neque molestiae quo aliquam voluptatum laboriosam qui cumque odio esse asperiores quidem totam ipsum.</p>
    </div>
</section>
  )
}
